In [5]:
import pandas as pd
data = pd.read_csv("jaipur.csv")
data.head()

,date_time,maxtempC,mintempC,totalSnow_cm,sunHour,uvIndex,uvIndex.1,moon_illumination,moonrise,moonset,...,WindChillC,WindGustKmph,cloudcover,humidity,precipMM,pressure,tempC,visibility,winddirDegree,windspeedKmph
0,2009-01-01 00:00:00,24,8,0.0,8.7,4,1,31,10:15 AM,10:03 PM,...,11,17,1,49,0.0,1017,9,10,4,8
1,2009-01-01 01:00:00,24,8,0.0,8.7,4,1,31,10:15 AM,10:03 PM,...,11,17,1,50,0.0,1017,9,10,3,8
2,2009-01-01 02:00:00,24,8,0.0,8.7,4,1,31,10:15 AM,10:03 PM,...,10,18,1,51,0.0,1017,9,10,2,8
3,2009-01-01 03:00:00,24,8,0.0,8.7,4,1,31,10:15 AM,10:03 PM,...,9,18,1,52,0.0,1017,8,10,1,9
4,2009-01-01 04:00:00,24,8,0.0,8.7,4,1,31,10:15 AM,10:03 PM,...,11,15,1,49,0.0,1018,10,10,1,8

In [6]:
data.isnull().any()

date_time            False
maxtempC             False
mintempC             False
totalSnow_cm         False
sunHour              False
uvIndex              False
uvIndex.1            False
moon_illumination    False
moonrise             False
moonset              False
sunrise              False
sunset               False
DewPointC            False
FeelsLikeC           False
HeatIndexC           False
WindChillC           False
WindGustKmph         False
cloudcover           False
humidity             False
precipMM             False
pressure             False
tempC                False
visibility           False
winddirDegree        False
windspeedKmph        False
dtype: bool

In [8]:
data.describe()

,maxtempC,mintempC,totalSnow_cm,sunHour,uvIndex,uvIndex.1,moon_illumination,DewPointC,FeelsLikeC,HeatIndexC,WindChillC,WindGustKmph,cloudcover,humidity,precipMM,pressure,tempC,visibility,winddirDegree,windspeedKmph
count,96432.000000,96432.000000,96432.0,96432.000000,96432.000000,96432.000000,96432.000000,96432.000000,96432.000000,96432.00000,96432.000000,96432.000000,96432.000000,96432.000000,96432.000000,96432.000000,96432.000000,96432.000000,96432.000000,96432.000000
mean,32.788701,21.469886,0.0,11.234769,6.776506,4.656711,46.094077,9.496474,28.293896,28.39490,27.667880,15.821003,14.510204,37.585190,0.030807,1008.475620,26.810353,9.958354,193.184296,10.440093
std,6.602928,7.482104,0.0,1.999857,1.500904,3.320682,31.249725,8.676747,8.543340,8.40839,7.940635,7.620975,20.461788,20.291609,0.264899,7.029146,8.221333,0.824028,105.847856,5.271046
min,15.000000,3.000000,0.0,3.900000,3.000000,1.000000,0.000000,-21.000000,5.000000,5.00000,5.000000,0.000000,0.000000,3.000000,0.000000,990.000000,0.000000,0.000000,0.000000,0.000000
25%,28.000000,15.000000,0.0,8.700000,6.000000,1.000000,18.000000,3.000000,22.000000,23.00000,22.000000,10.000000,0.000000,22.000000,0.000000,1002.000000,21.000000,10.000000,89.000000,7.000000
50%,33.000000,23.000000,0.0,11.600000,7.000000,5.000000,46.000000,8.000000,29.000000,29.00000,28.000000,15.000000,5.000000,34.000000,0.000000,1009.000000,28.000000,10.000000,226.000000,10.000000
75%,37.000000,27.000000,0.0,13.300000,8.000000,8.000000,73.000000,18.000000,35.000000,35.00000,33.000000,21.000000,22.000000,51.000000,0.000000,1015.000000,33.000000,10.000000,284.000000,13.000000
max,48.000000,36.000000,0.0,13.900000,10.000000,11.000000,100.000000,27.000000,61.000000,61.00000,52.000000,59.000000,100.000000,99.000000,17.000000,1026.000000,48.000000,20.000000,360.000000,44.000000

In [9]:
len(data)

96432

In [10]:
data.dtypes

date_time             object
maxtempC               int64
mintempC               int64
totalSnow_cm         float64
sunHour              float64
uvIndex                int64
uvIndex.1              int64
moon_illumination      int64
moonrise              object
moonset               object
sunrise               object
sunset                object
DewPointC              int64
FeelsLikeC             int64
HeatIndexC             int64
WindChillC             int64
WindGustKmph           int64
cloudcover             int64
humidity               int64
precipMM             float64
pressure               int64
tempC                  int64
visibility             int64
winddirDegree          int64
windspeedKmph          int64
dtype: object